bring v0.4
arkworks-rs/poly-commit pull request #110
Opened 2023-02-03 23:25 UTC by nikkolasg

## Description

Bring the crate to use ark_ec v0.4

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [] Wrote unit tests
- [] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2023-02-05 21:04 UTC, nikkolasg commented
BTW we also have a preliminary [branch](https://github.com/cryptonetlab/ark-polycommit/pull/1/) to do PST on the other base - commit in G2 opening in G1 - if you are interested

2023-02-06 10:33 UTC, maramihali commented
had a look at the multilinear PST, lgtm

2023-02-08 11:38 UTC, mmagician requested changes
mostly looks good! I left a few cleanup comments

2023-02-08 11:38 UTC, mmagician commented on src/sonic_pc/data_structures.rs
> +    fn serialize_compressed<W: Write>(&self, writer: W) -> Result<(), SerializationError> {
ditto

2023-02-15 16:46 UTC, Pratyush commented
I moved the commits to #112, which is merged now; thanks everyone for the work!

2023-02-15 16:46 UTC, closed without merging