Add benchmark templates and sample benches for IPA
arkworks-rs/poly-commit pull request #133
Opened 2023-10-26 11:08 UTC by mmagician

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

2023-10-26 16:46 UTC, Pratyush commented on benches/benches.rs
> +// #![cfg(feature = "benches")]
```suggestion
```

2023-10-26 16:47 UTC, Pratyush commented on Cargo.toml
> +rand_chacha = { version = "0.3.0", default-features = false, optional = true }
hm we don't want `criterion` as a normal dependency, as it has too many dependencies. `criterion` should be a dev-dependency.

2023-10-26 16:48 UTC, Pratyush commented on Cargo.toml
> +rand_chacha = { version = "0.3.0", default-features = false, optional = true }
Also, `rand_chacha` is already a dev-dependency.

2023-10-26 16:50 UTC, Pratyush commented on src/bench_templates/mod.rs
> +use ark_crypto_primitives::sponge::{
We can make this a file in `benches`, or extract it into a separate crate (ala `ark-algebra-bench-templates`)

2023-10-27 17:04 UTC, mmagician commented
Thanks @Pratyush, I've refactored the bench templates into its own crate as suggested. This required creating a workspace, so there's a bunch of files moved around, but ultimately the actual changes are few and much more elegant. Adding benches for a new scheme will also hopefully be simpler.

2023-10-28 16:24 UTC, Pratyush requested changes
Thanks for the change! The only thing that I think we should undo is the `pcs` renaming; it's fine to have the repo be called poly-commit and the folder within also called poly-commit.

2023-10-29 15:14 UTC, Pratyush approved these changes

2023-10-29 15:25 UTC, merged